### PR TITLE
Bulletproof routes

### LINKED ISSUE #286: make sure all routes will return something to the front end even if the server crashes

### PR DESCRIPTION
**Pull request by thomasmorgan**
closes #286 .

Also fixes an error in a previous merge!

### CODE REVIEW

**Comment by suchow** [comment]
Going through this now.

**Comment by suchow** [comment]
Nice work. I have a few suggestions for how to make this even better. The first is this:

If you find yourself copying and pasting the same code over and over within a file, it's probably best to refactor it into a new function. This principle is called DRY, don't repeat yourself (https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). It has many benefits. Each instance is guaranteed to be consistent. If there's a bug, you can fix it by changing the code in one place. The code is shorter. And it's easier to reason about.

In this case, you'll see that I've added a commit to this PR adding a function that builds an error response and prints some logging statements. I also changed one occurrence of the repeated pattern to use the new function. Can you go ahead and update the rest? You can find them all by searching for `traceback`.

If you're feeling ambitious, there's a second set of functions that we can refactor within `custom.py`: all the `400` responses.

**Comment by thomasmorgan** [comment]
done!

I beefed up the new function so now it can deal with both 400 errors and 403 errors, and did a bit of general tidying too.

**Comment by thomasmorgan** [comment]
this now closes #298  and #286

**Pull request merged**
