### PR TITLE
MCMCP

### PR DESCRIPTION
**Pull request by suchow**

### CODE REVIEW

**Comment by suchow** [comment]
@thomasmorgan 

Well, that was pleasant — it was simple to add a new set of Flask routes that place image-processing jobs on the queue (14058dd0c2d0a50e268f19101076fa8cc067bb2a). All that's missing is a front-end that POSTs and GETs to `/image`.

Can you take the next step of adjusting the networks here to have the desired structure?

**Comment by suchow** [comment]
@thomasmorgan Okay, I think this is ready to go. It's looking really nice!

I see two things we might want to improve. The first is the code that perturbs a newly created info:

```
        # TODO: find a more logical place for this code.
        perturbed = AnimalSource.perturb(info.contents, 0.1)
        new_info = ChoosableInfo(origin=self, contents=perturbed)
        Perturbation(info_in=info, info_out=new_info)
```

I don't think this belongs in the definition of the Agent, who has nothing to do with the generation of a new example similar to the one they selected. That seems like the role of the experiment. Do you know of any way to achieve that?

The second is that it would be slightly better if the previously chosen object and the perturbed version appeared on randomly chosen sides on each trial. As it stands, the selected one stays in place. That's not terrible, and maybe for the purpose of a demo it's not worth changing, but it might be.

Once we merge this, I'll create a new repo with the demo, add back in my backend routes, and then pass it along to @jcpeterson who can take it from there.

I think this came out pretty nicely.

**Comment by thomasmorgan** [comment]
@suchow how about we make the ChoosableInfo class an AnimalInfo class and the class has a perturbed_contents method, i.e. you would have:

old_info = self.infos()[0]
new_info = AnimalInfo(origin=self, contents=old_info.perturbed_contents())

This is how we handle mutation in previous experiments

**Comment by thomasmorgan** [comment]
oh, and as for side randomization, its not strictly consistent in the way you imagine - I this the perturbed info is always on the left, so if you choose that one, on the next trial it will be on the right.

As long as there are multiple chains I do not think this is an issue, but we could certainly add a bit of side randomization code

**Comment by thomasmorgan** [comment]
@suchow both done, let me know what you think

**Pull request merged**
