### PR TITLE
Handle Rollback and Close of SQLAlchemy Sessions

### PR DESCRIPTION
**Pull request by alecpm**
Adds a handler to rollback and close the session at the end of each request.  Simplifies session passing code.  This should address issue #224

### CODE REVIEW

**Comment by alecpm** [comment]
May also relate to #237

**Comment by suchow** [comment]
Launching this on Heroku produces the following error:

```
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:  2015-10-28 19:57:48,462 Exception in worker process: 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:  Traceback (most recent call last): 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      worker.init_process() 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      self.wsgi = self.app.wsgi() 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      self.callable = self.load() 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/src/psiturk/psiturk/experiment_server.py", line 52, in load 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      return util.import_app("psiturk.experiment:app") 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      __import__(module) 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/src/psiturk/psiturk/experiment.py", line 67, in <module> 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      from custom import custom_code 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/custom.py", line 34, in <module> 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      db.logger.setLevel(LOG_LEVEL) 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:  AttributeError: 'module' object has no attribute 'logger' 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:  Traceback (most recent call last): 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 495, in spawn_worker 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      worker.init_process() 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 106, in init_process 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      self.wsgi = self.app.wsgi() 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 114, in wsgi 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      self.callable = self.load() 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/src/psiturk/psiturk/experiment_server.py", line 52, in load 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      return util.import_app("psiturk.experiment:app") 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 354, in import_app 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      __import__(module) 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/.heroku/src/psiturk/psiturk/experiment.py", line 67, in <module> 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      from custom import custom_code 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:    File "/app/custom.py", line 34, in <module> 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:      db.logger.setLevel(LOG_LEVEL) 
Oct 28 12:57:48 w6a20f5f3-2933-4621-9298-dda2 app/web.1:  AttributeError: 'module' object has no attribute 'logger' 
```

**Comment by thomasmorgan** [comment]
@suchow it runs fine for me... any idea what might be different?

**Comment by cewing** [comment]
Is it possible that heroku did not get all the changes?  That error would suggest that the changes to wallace/db.py are not being seen by the updated wallace/custom.py

**Comment by thomasmorgan** [comment]
fixed: heroku requirements needed updating to pull the session-handling branch as opposed to master

**Comment by thomasmorgan** [comment]
OK, I've done some testing of the branch and it all runs fine. I am happy to merge it. Cris, you were going to do a review, right? Once you are happy we should merge.

When we spoke we discussed trying to ascertain whether this will stop the issues where some notifications end up not being processed. However, I'm pretty confident the only way to test this properly is to run a full study so that test will have to wait until the next experiment is ready.

**Comment by cewing** [comment]
Looks good to me.  Go ahead and ship it.

**Pull request merged**
